# Generated by Django 4.0.1 on 2022-01-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screed', '0003_statdefinition_rename_score_node_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdefinition',
            name='authors',
            field=models.ManyToManyField(to='Screed.User'),
        ),
        migrations.AddField(
            model_name='statdefinition',
            name='authors',
            field=models.ManyToManyField(to='Screed.User'),
        ),
    ]
