# Generated by Django 4.0.1 on 2022-01-23 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Screed', '0005_alter_choice_choice_check_alter_choice_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='stat_definition',
            new_name='definition',
        ),
        migrations.AlterField(
            model_name='choice',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Screed.node'),
        ),
    ]
