# Generated by Django 4.0.1 on 2022-01-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Screed', '0006_rename_stat_definition_stat_definition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_definition',
            new_name='definition',
        ),
    ]
