# Generated by Django 4.0.1 on 2022-01-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screed', '0007_rename_item_definition_item_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='title',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='edit',
            name='title',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
