# Generated by Django 4.0.1 on 2022-01-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Screed', '0008_alter_check_title_alter_edit_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='item_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Screed.itemdefinition'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='Screed.check'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Screed.user'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Screed.itemdefinition'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Screed.node'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Screed.node'),
        ),
    ]
